# generated by datamodel-codegen:
#   filename:  static_data.json
#   timestamp: 2022-08-27T21:17:51+00:00

from typing import Any, List, Optional

from pydantic import BaseModel


class ChipPlay(BaseModel):
    chip_name: str
    num_played: int


class TopElementInfoItem(BaseModel):
    id: int
    points: int


class Event(BaseModel):
    id: int
    name: str
    deadline_time: str
    average_entry_score: int
    finished: bool
    data_checked: bool
    highest_scoring_entry: Optional[int]
    deadline_time_epoch: int
    deadline_time_game_offset: int
    highest_score: Optional[int]
    is_previous: bool
    is_current: bool
    is_next: bool
    cup_leagues_created: bool
    h2h_ko_matches_created: bool
    chip_plays: List[ChipPlay]
    most_selected: Optional[int]
    most_transferred_in: Optional[int]
    top_element: Optional[int]
    top_element_info: Optional[TopElementInfoItem]
    transfers_made: int
    most_captained: Optional[int]
    most_vice_captained: Optional[int]


class GameSettings(BaseModel):
    league_join_private_max: int
    league_join_public_max: int
    league_max_size_public_classic: int
    league_max_size_public_h2h: int
    league_max_size_private_h2h: int
    league_max_ko_rounds_private_h2h: int
    league_prefix_public: str
    league_points_h2h_win: int
    league_points_h2h_lose: int
    league_points_h2h_draw: int
    league_ko_first_instead_of_random: bool
    cup_start_event_id: Any
    cup_stop_event_id: Any
    cup_qualifying_method: Any
    cup_type: Any
    squad_squadplay: int
    squad_squadsize: int
    squad_team_limit: int
    squad_total_spend: int
    ui_currency_multiplier: int
    ui_use_special_shirts: bool
    ui_special_shirt_exclusions: List
    stats_form_days: int
    sys_vice_captain_enabled: bool
    transfers_cap: int
    transfers_sell_on_fee: float
    league_h2h_tiebreak_stats: List[str]
    timezone: str


class Phase(BaseModel):
    id: int
    name: str
    start_event: int
    stop_event: int


class Team(BaseModel):
    code: int
    draw: int
    form: Any
    id: int
    loss: int
    name: str
    played: int
    points: int
    position: int
    short_name: str
    strength: int
    team_division: Any
    unavailable: bool
    win: int
    strength_overall_home: int
    strength_overall_away: int
    strength_attack_home: int
    strength_attack_away: int
    strength_defence_home: int
    strength_defence_away: int
    pulse_id: int


class Element(BaseModel):
    chance_of_playing_next_round: Optional[int]
    chance_of_playing_this_round: Optional[int]
    code: int
    cost_change_event: int
    cost_change_event_fall: int
    cost_change_start: int
    cost_change_start_fall: int
    dreamteam_count: int
    element_type: int
    ep_next: str
    ep_this: str
    event_points: int
    first_name: str
    form: str
    id: int
    in_dreamteam: bool
    news: str
    news_added: Optional[str]
    now_cost: int
    photo: str
    points_per_game: str
    second_name: str
    selected_by_percent: str
    special: bool
    squad_number: Any
    status: str
    team: int
    team_code: int
    total_points: int
    transfers_in: int
    transfers_in_event: int
    transfers_out: int
    transfers_out_event: int
    value_form: str
    value_season: str
    web_name: str
    minutes: int
    goals_scored: int
    assists: int
    clean_sheets: int
    goals_conceded: int
    own_goals: int
    penalties_saved: int
    penalties_missed: int
    yellow_cards: int
    red_cards: int
    saves: int
    bonus: int
    bps: int
    influence: str
    creativity: str
    threat: str
    ict_index: str
    influence_rank: int
    influence_rank_type: int
    creativity_rank: int
    creativity_rank_type: int
    threat_rank: int
    threat_rank_type: int
    ict_index_rank: int
    ict_index_rank_type: int
    corners_and_indirect_freekicks_order: Optional[int]
    corners_and_indirect_freekicks_text: str
    direct_freekicks_order: Optional[int]
    direct_freekicks_text: str
    penalties_order: Optional[int]
    penalties_text: str


class ElementStat(BaseModel):
    label: str
    name: str


class ElementType(BaseModel):
    id: int
    plural_name: str
    plural_name_short: str
    singular_name: str
    singular_name_short: str
    squad_select: int
    squad_min_play: int
    squad_max_play: int
    ui_shirt_specific: bool
    sub_positions_locked: List[int]
    element_count: int


class Summary(BaseModel):
    events: List[Event]
    game_settings: GameSettings
    phases: List[Phase]
    teams: List[Team]
    total_players: int
    elements: List[Element]
    element_stats: List[ElementStat]
    element_types: List[ElementType]


class TeamFixture(BaseModel):
    id: int
    code: int
    team_h: int
    team_h_score: Any
    team_a: int
    team_a_score: Any
    event: int
    finished: bool
    minutes: int
    provisional_start_time: bool
    kickoff_time: str
    event_name: str
    is_home: bool
    difficulty: int


class HistoryItem(BaseModel):
    element: int
    fixture: int
    opponent_team: int
    total_points: int
    was_home: bool
    kickoff_time: str
    team_h_score: int
    team_a_score: int
    round: int
    minutes: int
    goals_scored: int
    assists: int
    clean_sheets: int
    goals_conceded: int
    own_goals: int
    penalties_saved: int
    penalties_missed: int
    yellow_cards: int
    red_cards: int
    saves: int
    bonus: int
    bps: int
    influence: str
    creativity: str
    threat: str
    ict_index: str
    value: int
    transfers_balance: int
    selected: int
    transfers_in: int
    transfers_out: int


class HistoryPastItem(BaseModel):
    season_name: str
    element_code: int
    start_cost: int
    end_cost: int
    total_points: int
    minutes: int
    goals_scored: int
    assists: int
    clean_sheets: int
    goals_conceded: int
    own_goals: int
    penalties_saved: int
    penalties_missed: int
    yellow_cards: int
    red_cards: int
    saves: int
    bonus: int
    bps: int
    influence: str
    creativity: str
    threat: str
    ict_index: str


class PlayerFixtures(BaseModel):
    fixtures: List[TeamFixture]
    history: List[HistoryItem]
    history_past: List[HistoryPastItem]


class Pick(BaseModel):
    element: int
    position: int
    selling_price: int
    multiplier: int
    purchase_price: int
    is_captain: bool
    is_vice_captain: bool


class Chip(BaseModel):
    status_for_entry: str
    played_by_entry: List
    name: str
    number: int
    start_event: int
    stop_event: int
    chip_type: str


class Transfers(BaseModel):
    cost: int
    status: str
    limit: int
    made: int
    bank: int
    value: int


class MyTeam(BaseModel):
    picks: List[Pick]
    chips: List[Chip]
    transfers: Transfers


class AItem(BaseModel):
    value: int
    element: int


class HItem(BaseModel):
    value: int
    element: int


class Stat(BaseModel):
    identifier: str
    a: List[AItem]
    h: List[HItem]


class Fixture(BaseModel):
    code: int
    event: int
    finished: bool
    finished_provisional: bool
    id: int
    kickoff_time: str
    minutes: int
    provisional_start_time: bool
    started: bool
    team_a: int
    team_a_score: Optional[int]
    team_h: int
    team_h_score: Optional[int]
    stats: List[Stat]
    team_h_difficulty: int
    team_a_difficulty: int
    pulse_id: int
